development:
  adapter: mysql2
  database: sample_development
  username: root
  password: 
  pool: 5
  timeout: 5000


test:
  adapter: mysql2
  database: sample_test
  username: root
  password:
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: sample_production
  username: root
  password:
  pool: 5
  timeout: 5000
